cursor citations/registry/havens-1964-memo-on-the-religious-implications.json
cursor citations/registry/smith-1964-untitled.json
cursor citations/registry/bache-1981-on-the-emergence-of-perinatal-symptoms.json
cursor citations/registry/edwards-1986-the-case-against-reincarnation-parts-i-iv.json
cursor citations/registry/stolaroff-1999-untitled.json
cursor citations/registry/bache-1994-a-perinatal-interpretation-of-frightening-ndes.json
cursor citations/registry/harvey-2005-servant-of-a-transformed-future.json
cursor citations/registry/bache-2006-reincarnation-and-the-akashic-field.json
cursor citations/registry/grof-2012-two-case-studies-archetypal-astrology.json
cursor citations/registry/ferrer-2011-participation-metaphysics-and-enlightenment.json
cursor citations/registry/scientific-american-2014-end-the-ban-on-psychoactive-drug-research.json
cursor citations/registry/huxley-1954-the-doors-of-perception.json
cursor citations/registry/zaehner-1959-mysticism-sacred-and.json
cursor citations/registry/underhill-1961-mysticism.json
cursor citations/registry/clark-1969-chemical-mysticism.json
cursor citations/registry/waters-1970-masked-gods.json
cursor citations/registry/wambach-1978-reliving-past-lives.json
cursor citations/registry/stevenson-1983-cases-of-the.json
cursor citations/registry/whitton-1986-life-between-life.json
cursor citations/registry/almeder-1992-death-and-personal.json
cursor citations/registry/stevenson-1997-reincarnation-and-biology.json
cursor citations/registry/ferrer-2008-the-participatory-turn.json
cursor citations/registry/elgin-2001-promise-ahead.json
cursor citations/registry/almaas-2014-runaway-realization.json
cursor citations/registry/laszlo-2010-the-chaos-point.json
cursor citations/registry/clark-1964-religion-and-consciousness-expanding-substances.json
cursor citations/registry/bache-2014-reflections-on-the-mystery-of-death-and-rebirth.json
cursor citations/registry/bache-2011-the-collective-dynamics-of-contemplative-practice.json
cursor citations/registry/blewett-1959-handbook-for-the-therapeutic-use-of-lsd-25.json
cursor citations/registry/elliott-2019-worlds-26-richest-people-oxfam.json
cursor citations/registry/bache-2017-meet-the-professor-73-high-dose-lsd-sessions.json
